### PR TITLE
Porting my Node file system branch to MasterEric's repo

### PR DESCRIPTION
**Pull request by TamarCurry**
Per @MasterEric's request, attempting to merge adding Node file system support for Polymod. I'm still getting used to Github, so let me know if I did anything wrong.

### CODE REVIEW

**Comment by MasterEric** [comment]
Thank you for submitting! I will check this out (test it with my project along with your example) and if it seems good I'll merge it.

Then I can work with Lars on setting up everything else :)

**Comment by MasterEric** [comment]
@TamarCurry I downloaded `electron-v14.2.1-win32-x64` and added it to my path, then called `lime test electron` and got a white screen. When I opened the dev tools I saw the following output:

```
Uncaught ReferenceError: require is not defined
    at OpenFLSample.js:8290
    at $hx_script (OpenFLSample.js:79644)
    at Object.$hx_exports.lime.embed (OpenFLSample.js:79653)
    at index.html:40
VM76 renderer_init.js:97 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
```

**Comment by TamarCurry** [comment]
@MasterEric I had been making plain HTML5 builds and copy-pasting the generated files into a folder that has electron. Then I'd manually test against the main.js file with the command "electron.exe main.js".

I just tested with "lime build electron" and got the same results as you. I poked through the Lime Github repo and it looks like browser window's config arguments are hardcoded ([lines 52 through 64 in this file](https://github.com/haxelime/lime/blob/c743fe10c404fb73003e24100f319a472cb4203f/templates/electron/haxe/ElectronSetup.hx)) and there's currently no option to include "contextIsolation: false" in the webPreferences object that's created in lime/ElectronSetup.js. I believe contextIsolation is a relatively new addition to Electron, so that might be why it's not accounted for here. Setting contextIsolation to false is necessary in order for "require" to be defined and the app to run properly.

**Comment by MasterEric** [comment]
Hey, thanks for following up.

I'll put those instructions in the readme. I think in the long term we should look into adding a new option to Lime to provide the functionality you need to get this to work as expected with `lime test electron`

**Comment by MasterEric** [comment]
🎉 Congrats, once I followed your instructions, things looked to be running well! I have merged your changes into `develop`. 🎉

**Pull request merged**
